### ISSUE TITLE
HEI Identifiers: Identify all HEI's

### ISSUE THREAD

**Issue by jeroenvl** [Knowledge-Innovation-Centre/HEIDI#1]
## Actor

HEI, student, university staff

## Submitter

[European University Foundation](https://github.com/EuropeanUniversityFoundation)

## User Story

Most identifiers are currently scoped to a specific EU programme and maintained for identification within that scope. Ideally a system that allows for identifying EU as well as non-EU institutions beyond their participation in certain programmes / organisations would need to be established. 

## Restrictions

none

**Comment by anthonycamilleri** [comment]
Integrated into #2
