### ISSUE TITLE
HEI Identifiers: Provide users with a consistent and user-friendly list of HEI's

### ISSUE THREAD

**Issue by jeroenvl** [Knowledge-Innovation-Centre/HEIDI#2]
## Actor

HEI, student, university staff

## Submitter

[European University Foundation](https://github.com/EuropeanUniversityFoundation)

## User Story

In a student- or institution facing application datasets are often not complete / understandable. In some of the EC HEI datasets the names are available in English as well as in local language and also distinguishes the business name, should that be different from the legal name + official abbreviation.

## Restrictions

none

**Comment by anthonycamilleri** [comment]
@jeroenvl Issue has been addressed. If you could approve the commit, and further  provide specific examples of systems which use this, it would be helpful.
